Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/mansi/Documents/work/chat/chatapp/chatapp/core/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /test/populate/
[33mHTTP GET /test/populate/ 404 [0.01, 127.0.0.1:45744][0m
Not Found: /chat/api/newmessage/
[33mHTTP GET /chat/api/newmessage/ 404 [0.00, 127.0.0.1:45744][0m
/home/sarath/Documents/Chat-App/apps/chat/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /chat/api/newmessage/
[31;1mHTTP GET /chat/api/newmessage/ 405 [0.04, 127.0.0.1:45840][0m
[mHTTP GET /static/rest_framework/css/bootstrap.min.css 200 [0.01, 127.0.0.1:45840][0m
[mHTTP GET /static/rest_framework/css/bootstrap-tweaks.css 200 [0.01, 127.0.0.1:45842][0m
[mHTTP GET /static/rest_framework/css/prettify.css 200 [0.01, 127.0.0.1:45844][0m
[mHTTP GET /static/rest_framework/css/default.css 200 [0.01, 127.0.0.1:45846][0m
[mHTTP GET /static/rest_framework/js/jquery-3.5.1.min.js 200 [0.01, 127.0.0.1:45848][0m
[mHTTP GET /static/rest_framework/js/ajax-form.js 200 [0.01, 127.0.0.1:45850][0m
[mHTTP GET /static/rest_framework/js/csrf.js 200 [0.01, 127.0.0.1:45840][0m
[mHTTP GET /static/rest_framework/js/bootstrap.min.js 200 [0.01, 127.0.0.1:45842][0m
[mHTTP GET /static/rest_framework/js/prettify-min.js 200 [0.01, 127.0.0.1:45844][0m
[mHTTP GET /static/rest_framework/js/default.js 200 [0.01, 127.0.0.1:45846][0m
[36mHTTP GET /static/rest_framework/img/grid.png 304 [0.00, 127.0.0.1:45842][0m
Watching for file changes with StatReloader
Method Not Allowed: /chat/api/newmessage/
[31;1mHTTP GET /chat/api/newmessage/ 405 [0.03, 127.0.0.1:45858][0m
Bad Request: /chat/api/newmessage/
[31;1mHTTP POST /chat/api/newmessage/ 400 [0.02, 127.0.0.1:46200][0m
/home/sarath/Documents/Chat-App/apps/chat/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/sarath/Documents/Chat-App/apps/chat/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/sarath/Documents/Chat-App/apps/chat/views.py changed, reloading.
Watching for file changes with StatReloader
/home/sarath/Documents/Chat-App/apps/chat/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/sarath/Documents/Chat-App/apps/chat/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /test/populate/
[33mHTTP GET /test/populate/ 404 [0.02, 127.0.0.1:46426][0m
[mHTTP GET /chat/ 200 [0.00, 127.0.0.1:46426][0m
Not Found: /chat/api/getmessage/
[33mHTTP GET /chat/api/getmessage/ 404 [0.01, 127.0.0.1:46426][0m
Internal Server Error: /chat/api/getmessages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'GetMessageView' should either include a `queryset` attribute, or override the `get_queryset()` method.
[35;1mHTTP GET /chat/api/getmessages/ 500 [0.03, 127.0.0.1:46426][0m
/home/sarath/Documents/Chat-App/apps/chat/views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /chat/api/getmessages/
[31;1mHTTP GET /chat/api/getmessages/ 405 [0.02, 127.0.0.1:46554][0m
Method Not Allowed: /chat/api/getmessages/
[31;1mHTTP GET /chat/api/getmessages/?id=1 405 [0.01, 127.0.0.1:46554][0m
Method Not Allowed: /chat/api/getmessages/
[31;1mHTTP GET /chat/api/getmessages/?id=1/ 405 [0.02, 127.0.0.1:46554][0m
/home/sarath/Documents/Chat-App/apps/chat/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /chat/api/getmessages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
TypeError: get_queryset() missing 1 required positional argument: 'request'
[35;1mHTTP GET /chat/api/getmessages/?id=1/ 500 [0.04, 127.0.0.1:46564][0m
Internal Server Error: /chat/api/getmessages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
TypeError: get_queryset() missing 1 required positional argument: 'request'
[35;1mHTTP GET /chat/api/getmessages/?id=1 500 [0.03, 127.0.0.1:46564][0m
/home/sarath/Documents/Chat-App/apps/chat/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /chat/api/getmessages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[35;1mHTTP GET /chat/api/getmessages/?id=1 500 [0.04, 127.0.0.1:46574][0m
Internal Server Error: /chat/api/getmessages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[35;1mHTTP GET /chat/api/getmessages/?id=1 500 [0.03, 127.0.0.1:46592][0m
/home/sarath/Documents/Chat-App/apps/chat/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /chat/api/getmessages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[35;1mHTTP GET /chat/api/getmessages/?id=1 500 [0.04, 127.0.0.1:46604][0m
Internal Server Error: /chat/api/getmessages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[35;1mHTTP GET /chat/api/getmessages/ 500 [0.03, 127.0.0.1:46646][0m
Internal Server Error: /chat/api/getmessages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[35;1mHTTP GET /chat/api/getmessages/?id=1 500 [0.03, 127.0.0.1:46654][0m
Internal Server Error: /chat/api/getmessages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[35;1mHTTP GET /chat/api/getmessages/ 500 [0.03, 127.0.0.1:47060][0m
[32mHTTP GET /admin/ 302 [0.01, 127.0.0.1:47640][0m
[mHTTP GET /admin/login/?next=/admin/ 200 [0.02, 127.0.0.1:47640][0m
[mHTTP GET /static/admin/css/base.css 200 [0.01, 127.0.0.1:47640][0m
[mHTTP GET /static/admin/css/nav_sidebar.css 200 [0.01, 127.0.0.1:47642][0m
[mHTTP GET /static/admin/css/login.css 200 [0.01, 127.0.0.1:47644][0m
[mHTTP GET /static/admin/css/responsive.css 200 [0.01, 127.0.0.1:47646][0m
[mHTTP GET /static/admin/js/nav_sidebar.js 200 [0.00, 127.0.0.1:47644][0m
[mHTTP GET /static/admin/css/fonts.css 200 [0.01, 127.0.0.1:47646][0m
[mHTTP GET /static/admin/fonts/Roboto-Regular-webfont.woff 200 [0.00, 127.0.0.1:47646][0m
[mHTTP GET /static/admin/fonts/Roboto-Light-webfont.woff 200 [0.00, 127.0.0.1:47644][0m
[32mHTTP POST /admin/login/?next=/admin/ 302 [0.08, 127.0.0.1:48540][0m
[mHTTP GET /admin/ 200 [0.02, 127.0.0.1:48540][0m
[mHTTP GET /static/admin/css/dashboard.css 200 [0.00, 127.0.0.1:48540][0m
[mHTTP GET /static/admin/img/icon-addlink.svg 200 [0.00, 127.0.0.1:48540][0m
[mHTTP GET /static/admin/img/icon-changelink.svg 200 [0.00, 127.0.0.1:48542][0m
[mHTTP GET /static/admin/fonts/Roboto-Bold-webfont.woff 200 [0.00, 127.0.0.1:48544][0m
[mHTTP GET /admin/auth/user/add/ 200 [0.04, 127.0.0.1:48544][0m
[mHTTP GET /static/admin/css/forms.css 200 [0.00, 127.0.0.1:48544][0m
[mHTTP GET /static/admin/js/vendor/jquery/jquery.js 200 [0.01, 127.0.0.1:48540][0m
[mHTTP GET /static/admin/js/jquery.init.js 200 [0.01, 127.0.0.1:48552][0m
[mHTTP GET /static/admin/js/core.js 200 [0.01, 127.0.0.1:48554][0m
[mHTTP GET /static/admin/js/admin/RelatedObjectLookups.js 200 [0.01, 127.0.0.1:48556][0m
[mHTTP GET /static/admin/js/actions.js 200 [0.01, 127.0.0.1:48544][0m
[mHTTP GET /static/admin/css/widgets.css 200 [0.01, 127.0.0.1:48540][0m
[mHTTP GET /static/admin/js/urlify.js 200 [0.01, 127.0.0.1:48552][0m
[mHTTP GET /static/admin/js/prepopulate.js 200 [0.01, 127.0.0.1:48554][0m
[mHTTP GET /static/admin/js/vendor/xregexp/xregexp.js 200 [0.01, 127.0.0.1:48556][0m
[mHTTP GET /static/admin/js/prepopulate_init.js 200 [0.01, 127.0.0.1:48544][0m
[mHTTP GET /static/admin/js/change_form.js 200 [0.00, 127.0.0.1:48544][0m
[mHTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:48542][0m
[32mHTTP POST /admin/auth/user/add/ 302 [0.08, 127.0.0.1:48542][0m
[mHTTP GET /admin/auth/user/3/change/ 200 [0.04, 127.0.0.1:48542][0m
[mHTTP GET /static/admin/js/calendar.js 200 [0.00, 127.0.0.1:48544][0m
[mHTTP GET /static/admin/js/admin/DateTimeShortcuts.js 200 [0.01, 127.0.0.1:48556][0m
[mHTTP GET /static/admin/js/SelectBox.js 200 [0.01, 127.0.0.1:48554][0m
[mHTTP GET /static/admin/js/SelectFilter2.js 200 [0.01, 127.0.0.1:48552][0m
[mHTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:48542][0m
[mHTTP GET /static/admin/img/icon-yes.svg 200 [0.00, 127.0.0.1:48542][0m
[mHTTP GET /static/admin/img/icon-unknown.svg 200 [0.01, 127.0.0.1:48542][0m
[mHTTP GET /static/admin/img/search.svg 200 [0.01, 127.0.0.1:48552][0m
[mHTTP GET /static/admin/img/selector-icons.svg 200 [0.01, 127.0.0.1:48554][0m
[mHTTP GET /static/admin/img/icon-unknown-alt.svg 200 [0.01, 127.0.0.1:48556][0m
[mHTTP GET /static/admin/img/icon-calendar.svg 200 [0.02, 127.0.0.1:48544][0m
[mHTTP GET /static/admin/img/icon-clock.svg 200 [0.02, 127.0.0.1:48540][0m
[mHTTP GET /admin/auth/user/ 200 [0.05, 127.0.0.1:48540][0m
[mHTTP GET /static/admin/css/changelists.css 200 [0.00, 127.0.0.1:48540][0m
[mHTTP GET /static/admin/img/icon-no.svg 200 [0.00, 127.0.0.1:48540][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:48544][0m
[mHTTP GET /static/admin/img/tooltag-add.svg 200 [0.00, 127.0.0.1:48544][0m
[mHTTP GET /static/admin/img/sorting-icons.svg 200 [0.00, 127.0.0.1:48540][0m
[mHTTP GET /admin/auth/group/ 200 [0.03, 127.0.0.1:48540][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:48540][0m
[mHTTP GET /admin/auth/group/add/ 200 [0.04, 127.0.0.1:48540][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:48540][0m
[32mHTTP POST /admin/auth/group/add/ 302 [0.01, 127.0.0.1:48540][0m
[mHTTP GET /admin/auth/group/ 200 [0.02, 127.0.0.1:48540][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:48540][0m
[mHTTP GET /admin/auth/group/1/change/ 200 [0.04, 127.0.0.1:48540][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:48540][0m
[mHTTP GET /admin/auth/group/ 200 [0.03, 127.0.0.1:48540][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:48540][0m
[mHTTP GET /admin/auth/group/add/ 200 [0.03, 127.0.0.1:48540][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:48540][0m
[32mHTTP POST /admin/auth/group/add/ 302 [0.02, 127.0.0.1:48540][0m
[mHTTP GET /admin/auth/group/ 200 [0.02, 127.0.0.1:48540][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:48540][0m
[mHTTP GET /admin/auth/user/ 200 [0.04, 127.0.0.1:48540][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:48540][0m
[mHTTP GET /admin/auth/user/add/ 200 [0.06, 127.0.0.1:48540][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:48540][0m
[mHTTP GET /chat/ 200 [0.01, 127.0.0.1:48540][0m
Internal Server Error: /chat/api/getmessages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[35;1mHTTP GET /chat/api/getmessages/ 500 [0.03, 127.0.0.1:49062][0m
Not Found: /test/populate/
[33mHTTP GET /test/populate/ 404 [0.01, 127.0.0.1:49290][0m
Not Found: /chat/api/newmessages/
[33mHTTP GET /chat/api/newmessages/ 404 [0.01, 127.0.0.1:49296][0m
Method Not Allowed: /chat/api/newmessage/
[31;1mHTTP GET /chat/api/newmessage/ 405 [0.02, 127.0.0.1:49296][0m
[mHTTP GET /admin/auth/user/ 200 [0.04, 127.0.0.1:49296][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49296][0m
[mHTTP GET /admin/auth/group/ 200 [0.03, 127.0.0.1:49296][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49296][0m
[mHTTP GET /admin/auth/user/ 200 [0.04, 127.0.0.1:49296][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49296][0m
[mHTTP GET /admin/auth/user/add/ 200 [0.03, 127.0.0.1:49296][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49296][0m
[mHTTP GET /admin/auth/group/ 200 [0.03, 127.0.0.1:49316][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49316][0m
[mHTTP GET /admin/auth/user/ 200 [0.04, 127.0.0.1:49316][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49316][0m
[mHTTP GET /admin/auth/user/3/change/ 200 [0.05, 127.0.0.1:49316][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49316][0m
[32mHTTP POST /admin/auth/user/3/change/ 302 [0.03, 127.0.0.1:49316][0m
[mHTTP GET /admin/auth/user/ 200 [0.02, 127.0.0.1:49316][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49316][0m
Method Not Allowed: /chat/api/newmessage/
[31;1mHTTP GET /chat/api/newmessage/ 405 [0.03, 127.0.0.1:49316][0m
/home/sarath/Documents/Chat-App/apps/chat/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /chat/api/messages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[35;1mHTTP GET /chat/api/messages/ 500 [0.04, 127.0.0.1:49418][0m
[mHTTP GET /admin/auth/user/ 200 [0.04, 127.0.0.1:49502][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49502][0m
[mHTTP GET /admin/auth/user/3/change/ 200 [0.05, 127.0.0.1:49502][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49502][0m
[32mHTTP POST /admin/auth/user/3/change/ 302 [0.04, 127.0.0.1:49502][0m
[mHTTP GET /admin/auth/user/ 200 [0.03, 127.0.0.1:49502][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49502][0m
[mHTTP GET /admin/auth/user/1/change/ 200 [0.05, 127.0.0.1:49502][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49502][0m
[mHTTP GET /admin/auth/group/ 200 [0.04, 127.0.0.1:49502][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49502][0m
[mHTTP GET /admin/auth/group/1/change/ 200 [0.03, 127.0.0.1:49502][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49502][0m
[mHTTP GET /admin/auth/user/ 200 [0.04, 127.0.0.1:49502][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49502][0m
/home/sarath/Documents/Chat-App/apps/chat/admin.py changed, reloading.
Watching for file changes with StatReloader
/home/sarath/Documents/Chat-App/apps/chat/admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[mHTTP GET /admin/auth/user/ 200 [0.04, 127.0.0.1:49630][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49630][0m
[mHTTP GET /admin/chat/group/ 200 [0.02, 127.0.0.1:49630][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49630][0m
[mHTTP GET /admin/chat/group/add/ 200 [0.03, 127.0.0.1:49630][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49630][0m
[32mHTTP POST /admin/chat/group/add/ 302 [0.02, 127.0.0.1:49630][0m
[mHTTP GET /admin/chat/group/ 200 [0.02, 127.0.0.1:49630][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49630][0m
[mHTTP GET /admin/auth/user/ 200 [0.04, 127.0.0.1:49630][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49630][0m
[mHTTP GET /admin/auth/user/3/change/ 200 [0.06, 127.0.0.1:49630][0m
[mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:49630][0m
[mHTTP GET /admin/ 200 [0.02, 127.0.0.1:49630][0m
Method Not Allowed: /chat/api/newmessage/
[31;1mHTTP GET /chat/api/newmessage/ 405 [0.02, 127.0.0.1:49630][0m
[mHTTP POST /chat/api/newmessage/ 201 [0.03, 127.0.0.1:49630][0m
[mHTTP POST /chat/api/newmessage/ 201 [0.02, 127.0.0.1:49630][0m
Internal Server Error: /chat/api/messages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[35;1mHTTP GET /chat/api/messages/ 500 [0.03, 127.0.0.1:49722][0m
/home/sarath/Documents/Chat-App/apps/chat/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /chat/api/messages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[35;1mHTTP GET /chat/api/messages/ 500 [0.04, 127.0.0.1:49962][0m
Internal Server Error: /chat/api/messages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[35;1mHTTP GET /chat/api/messages/ 500 [0.03, 127.0.0.1:49962][0m
Internal Server Error: /chat/api/messages/
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[35;1mHTTP GET /chat/api/messages/?id=1/ 500 [0.06, 127.0.0.1:49962][0m
/home/sarath/Documents/Chat-App/apps/chat/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/sarath/Documents/Chat-App/apps/chat/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /chat/api/messages/1/
[33mHTTP GET /chat/api/messages/1/ 404 [0.01, 127.0.0.1:50006][0m
Internal Server Error: /chat/api/messages/1
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
TypeError: get_queryset() missing 1 required positional argument: 'group_id'
[35;1mHTTP GET /chat/api/messages/1 500 [0.06, 127.0.0.1:50006][0m
/home/sarath/Documents/Chat-App/apps/chat/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /chat/api/messages/1
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
TypeError: get_queryset() missing 1 required positional argument: 'group_id'
[35;1mHTTP GET /chat/api/messages/1 500 [0.04, 127.0.0.1:50026][0m
/home/sarath/Documents/Chat-App/apps/chat/views.py changed, reloading.
Watching for file changes with StatReloader
/home/sarath/Documents/Chat-App/apps/chat/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /chat/api/messages/1
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() got multiple values for argument 'group_id'
[35;1mHTTP GET /chat/api/messages/1 500 [0.04, 127.0.0.1:50052][0m
/home/sarath/Documents/Chat-App/apps/chat/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /chat/api/messages/1
Traceback (most recent call last):
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 263, in _get_response_async
    response = await sync_to_async(response.render, thread_sensitive=True)()
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/renderers.py", line 680, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/renderers.py", line 413, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 439, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/sarath/Documents/Chat-App/chat-app/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Message is not JSON serializable
[35;1mHTTP GET /chat/api/messages/1 500 [0.06, 127.0.0.1:50064][0m
/home/sarath/Documents/Chat-App/apps/chat/views.py changed, reloading.
Watching for file changes with StatReloader
[mHTTP GET /chat/api/messages/1 200 [0.02, 127.0.0.1:50084][0m
